POST  http://127.0.0.1:8000/member/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "逢霖",
    "password": "123"
}

###
POST http://127.0.0.1:8000/store/stores/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MjIxMzAwLCJpYXQiOjE3NjQyMjEwMDAsImp0aSI6IjQ4OTMwZmQyZGE1NjRiYmZhY2U2OGEwZjdmY2E5YzdkIiwidXNlcl9pZCI6IjciLCJyb2xlIjoibWVyY2hhbnQifQ.5LSOk2WzITni9xX3SMG67_PhwmEtHIfAJ5kB54vVDk8

{
    "store_name": "帶帶黑狗的店",
    "store_description": "這是一家黑狗帶帶很愛的店喔！"

}

###

PUT http://127.0.0.1:8000/store/stores/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MjIxNTUxLCJpYXQiOjE3NjQyMjEyNTEsImp0aSI6ImY0ZDQwMWQxYTMzNjQ4MTU4ZTIzMjQwYjg2OWMzOWI5IiwidXNlcl9pZCI6IjciLCJyb2xlIjoibWVyY2hhbnQifQ.ClxoPKRvftaVf6yh2G7L04DGUyFGrsbv1aWKBLVROGo

{
    "store_name": "tie的店",
    "store_description": "這是一家黑狗tietie的店喔！"

}

###

DELETE  http://127.0.0.1:8000/store/stores/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MjIxMzAwLCJpYXQiOjE3NjQyMjEwMDAsImp0aSI6IjQ4OTMwZmQyZGE1NjRiYmZhY2U2OGEwZjdmY2E5YzdkIiwidXNlcl9pZCI6IjciLCJyb2xlIjoibWVyY2hhbnQifQ.5LSOk2WzITni9xX3SMG67_PhwmEtHIfAJ5kB54vVDk8

###
POST http://127.0.0.1:8000/store/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NTc0NDU5LCJpYXQiOjE3NjQ1NzQxNTksImp0aSI6IjlkNWQ1YTQ1ZDhmMTQ5YmY4OGI4MjI2ZjBjMzZiYTc2IiwidXNlcl9pZCI6IjEiLCJyb2xlIjoibWVyY2hhbnQifQ.6zxKyWIgyopTIRq4oCdifJFB_4GQK9PTWfOKBrziYXI

{
    "name": "Q彈潔牙骨",
    "description": "領帶超愛的潔牙骨",
    "price": 2.99,
    "stock": 10
}

###
PUT http://127.0.0.1:8000/store/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTQ3MDM3LCJpYXQiOjE3NjQxNDY3MzcsImp0aSI6IjkxYzkzYTcwNzkxODQ4ZGE5Y2RlMDRjOWRhZjM1NDc2IiwidXNlcl9pZCI6IjciLCJyb2xlIjoibWVyY2hhbnQifQ.AyBEkhKQtCZ5omU3JXbXxCJHqM1OD0J_7G2RApGbIPk

{
    "name": "難吃的狗糧",
    "description": "領帶不愛吃的狗糧",
    "price": 1.99,
    "stock": 5000
}

###
PUT http://127.0.0.1:8000/member/members/1/ HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NTc0NjQyLCJpYXQiOjE3NjQ1NzQzNDIsImp0aSI6ImNkOTVhOGM2YTgzNjQ1OGFiYjA2YzVhMDgwZjZkOGY3IiwidXNlcl9pZCI6IjIiLCJyb2xlIjoibWVtYmVyIn0.AWVMz6n1--w8b6LVjOHAVl_ZbAZqCHsDl6vjjNjjk04

{
    "member_name": "逢霖",
    "member_email": "Wu@gmail.com",
    "member_birth": "1991-10-30",
    "member_avatar": "empty.png"
}

###
POST http://127.0.0.1:8000/store/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NTc1MDI3LCJpYXQiOjE3NjQ1NzQ3MjcsImp0aSI6Ijc2ZDlhYWI0OGE3MDQxZmE4ZDY0NGNiNGVmZThlYTEyIiwidXNlcl9pZCI6IjIiLCJyb2xlIjoibWVtYmVyIn0.EZHs-1e68jqr1VmHlJwDg5TDrYokNroygDYP9sP2Y3M

{
    "status": "Pending",
    "items": [
        {
            "product": 1,
            "quantity": 2
        },
        {
            "product": 2,
            "quantity": 1
        }
    ]
}

###
GET http://127.0.0.1:8000/store/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0NTc1MDI3LCJpYXQiOjE3NjQ1NzQ3MjcsImp0aSI6Ijc2ZDlhYWI0OGE3MDQxZmE4ZDY0NGNiNGVmZThlYTEyIiwidXNlcl9pZCI6IjIiLCJyb2xlIjoibWVtYmVyIn0.EZHs-1e68jqr1VmHlJwDg5TDrYokNroygDYP9sP2Y3M