POST  http://127.0.0.1:8000/member/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "fun",
    "password": "123"
}

###
GET  http://127.0.0.1:8000/store/stores/ HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:8000/store/stores/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjEwMzc5LCJpYXQiOjE3NjU2MTAwNzksImp0aSI6IjAyYjdkYWMyYTNiYTRmZjlhNjFkMzEzZmI2MzhhYmQzIiwidXNlcl9pZCI6IjEiLCJyb2xlIjoibWVyY2hhbnQifQ.lOou4xJZcBlprykCiMDBUQY3ZjyNbdBEEsAB4pkE968

{
    "name": "帶帶黑狗的店",
    "description": "這是一家黑狗帶帶很愛的店喔！",
    "address": "高雄市三民區大連街373號6樓"

}

###

PATCH  http://127.0.0.1:8000/store/stores/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NjAyNTQwLCJpYXQiOjE3Njc2MDIyNDAsImp0aSI6ImYyODFjNjBjYTljYzQyODdiMTAyNzUxNjdkNDAwMDM1IiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.70-m7Q1wgJVBihjb6UILSCXuZrnHvVnDAo_G8Q4b7VI

{

    "address": "高雄市高雄區高雄街100號10樓"

}

###
GET   http://127.0.0.1:8000/store/stores/1/ HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:8000/store/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjEzNTExLCJpYXQiOjE3NjU2MTMyMTEsImp0aSI6IjBiMjQwMDQ2MjBlMDRkNjk4ZTNkNDAzNzg3ZDgxNWE2IiwidXNlcl9pZCI6IjIiLCJyb2xlIjoibWVyY2hhbnQifQ.W2_Mw4oeE4j_dehej8VNyGKPGVVy3cZJ3Cr8-Kik_P0

{
    "name": "起司凍乾",
    "description": "濃郁起司，狗狗peace",
    "price": 5.99,
    "stock": 35
}

###
GET http://127.0.0.1:8000/store/products/ HTTP/1.1
Content-Type: application/json

###
PATCH  http://127.0.0.1:8000/store/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NjAxMzAwLCJpYXQiOjE3Njc2MDEwMDAsImp0aSI6ImRjYWExZjVhOGJmZDQ3ZDZiOTFhNjExYjU5YjRiMTdiIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.yT-6OUXyL2VfUxWLYTR2_f34e_vdGQ_D0EqHqJMuEWw

{

    "stock": 20
}

###
GET http://127.0.0.1:8000/store/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzM3Mzg5LCJpYXQiOjE3Njg3MzcwODksImp0aSI6IjJiYTUyYmI2OWFmNTQ5ZGY5MTQ2MmRlNGNjZWExZTNkIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.3dOb6MTgXvqlMF8AWQmvfeqpwGfhGpbmLEzoHPsUaok

###
POST http://127.0.0.1:8000/store/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NjAxMzAwLCJpYXQiOjE3Njc2MDEwMDAsImp0aSI6ImRjYWExZjVhOGJmZDQ3ZDZiOTFhNjExYjU5YjRiMTdiIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.yT-6OUXyL2VfUxWLYTR2_f34e_vdGQ_D0EqHqJMuEWw

{
    "status": "paid",
    "receiver_name": "吳逢霖",
    "receiver_phone": "0912345678",
    "address": "高雄市高雄區高雄路100號",
    "items": [
        {
            "product": 3,
            "quantity": 2
        },
        {
            "product": 4,
            "quantity": 1
        }
    ]
}

###
GET http://127.0.0.1:8000/store/orders/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzQwMTk2LCJpYXQiOjE3Njg3Mzk4OTYsImp0aSI6IjU3MzllMDJiMTliODRjNmQ5OWEzNDdmNWM1YTU0M2YwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.HCK_Yaqqqm__dpV_RyEUzwlPxfI5_KD1F0hX8jY2LR0

###
PATCH  http://127.0.0.1:8000/store/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NzQwMTk2LCJpYXQiOjE3Njg3Mzk4OTYsImp0aSI6IjU3MzllMDJiMTliODRjNmQ5OWEzNDdmNWM1YTU0M2YwIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.HCK_Yaqqqm__dpV_RyEUzwlPxfI5_KD1F0hX8jY2LR0

{
    "address": "高雄市高雄區高雄路200號"
}

###
GET http://127.0.0.1:8000/member/members/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NjAxMTQ4LCJpYXQiOjE3Njc2MDA4NDgsImp0aSI6IjA3NmI3YmJlOTUxMzQ4MTA4MDg3MTdhMzVjNTU2Zjc4IiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.Wz5_q10PKzsOpFRcKPP22fhprD5RYO-HudGDrP0fCWc


###
PUT  http://127.0.0.1:8000/member/members/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NjAxNTE2LCJpYXQiOjE3Njc2MDEyMTYsImp0aSI6IjQwNTk5NzIwNmUwMzQ0NWJhMTNhMjgyMTAxZjg2MTZkIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoibWVtYmVyIn0.C0FRJ4roYchXLAjgFSGL5tcGbnPg65-ENARvPgVyjlU

{
    "name": "陳小魚",
    "birthday": "1992-09-25",
    "member_avatar": "empty.png",
    "address": "台南市台南區台南路100號",
    "phone_num": "0987654321"

}