# Generated by Django 5.2.7 on 2025-11-25 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 25, 23, 16, 43, 303508),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 25, 23, 16, 43, 303508)
            ),
        ),
    ]
