# Generated by Django 5.2.7 on 2025-12-13 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 13, 15, 40, 49, 493427)
            ),
        ),
    ]
