# Generated by Django 4.2.11 on 2025-10-14 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_name", models.CharField(max_length=20)),
                ("member_password", models.CharField(max_length=128)),
                ("member_email", models.EmailField(max_length=200, unique=True)),
                ("member_birth", models.DateField()),
                (
                    "member_avatar",
                    models.CharField(default="empty.png", max_length=100),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 10, 14, 9, 46, 1, 526846)
                    ),
                ),
                ("member_points", models.IntegerField(default=0)),
                ("login_days", models.IntegerField(default=0)),
                (
                    "last_loginDate",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 10, 14, 9, 46, 1, 526846)
                    ),
                ),
            ],
            options={
                "db_table": "member",
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("merchant_id", models.AutoField(primary_key=True, serialize=False)),
                ("merchant_name", models.CharField(max_length=20)),
                ("merchant_password", models.CharField(max_length=128)),
                ("merchant_email", models.EmailField(max_length=200, unique=True)),
                ("merchant_birth", models.DateField()),
                (
                    "merchant_avatar",
                    models.CharField(default="empty.png", max_length=100),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 10, 14, 9, 46, 1, 526846)
                    ),
                ),
                ("login_days", models.IntegerField(default=0)),
                (
                    "last_loginDate",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 10, 14, 9, 46, 1, 526846)
                    ),
                ),
            ],
            options={
                "db_table": "merchant",
            },
        ),
    ]
