# Generated by Django 5.2.7 on 2025-11-25 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="last_loginDate",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 25, 23, 16, 43, 302512),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 25, 23, 16, 43, 302512),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_points",
            field=models.IntegerField(default=50, editable=False),
        ),
    ]
