# Generated by Django 5.2.7 on 2025-11-15 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="last_loginDate",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 28, 8, 747574)
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 28, 8, 747574)
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="last_loginDate",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 28, 8, 747574)
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 28, 8, 747574)
            ),
        ),
    ]
