# Generated by Django 5.2.7 on 2025-11-15 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "member",
            "0002_alter_member_last_logindate_alter_member_last_update_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="last_loginDate",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 29, 31, 196345),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 29, 31, 196345),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="login_days",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_points",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="last_loginDate",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 29, 31, 196345)
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 11, 15, 22, 29, 31, 196345)
            ),
        ),
    ]
